//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductDiscriptionField;
        
        private int StockQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProductDiscription {
            get {
                return this.ProductDiscriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDiscriptionField, value) != true)) {
                    this.ProductDiscriptionField = value;
                    this.RaisePropertyChanged("ProductDiscription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StockQuantity {
            get {
                return this.StockQuantityField;
            }
            set {
                if ((this.StockQuantityField.Equals(value) != true)) {
                    this.StockQuantityField = value;
                    this.RaisePropertyChanged("StockQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", ConfigurationName="ServiceReferenceWSTwo.AWebServiceToHandleDBSoap")]
    public interface AWebServiceToHandleDBSoap {
        
        // CODEGEN: Generating message contract since element name DisplayAllProductsResult from namespace LU_SYSA14_2020_IntegrationTechnologies_CSG19 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/DisplayAllProducts", ReplyAction="*")]
        LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsResponse DisplayAllProducts(LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/DisplayAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsResponse> DisplayAllProductsAsync(LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisplayAllProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DisplayAllProducts", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequestBody Body;
        
        public DisplayAllProductsRequest() {
        }
        
        public DisplayAllProductsRequest(LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DisplayAllProductsRequestBody {
        
        public DisplayAllProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisplayAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DisplayAllProductsResponse", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsResponseBody Body;
        
        public DisplayAllProductsResponse() {
        }
        
        public DisplayAllProductsResponse(LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class DisplayAllProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.Product[] DisplayAllProductsResult;
        
        public DisplayAllProductsResponseBody() {
        }
        
        public DisplayAllProductsResponseBody(LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.Product[] DisplayAllProductsResult) {
            this.DisplayAllProductsResult = DisplayAllProductsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AWebServiceToHandleDBSoapChannel : LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.AWebServiceToHandleDBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AWebServiceToHandleDBSoapClient : System.ServiceModel.ClientBase<LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.AWebServiceToHandleDBSoap>, LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.AWebServiceToHandleDBSoap {
        
        public AWebServiceToHandleDBSoapClient() {
        }
        
        public AWebServiceToHandleDBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AWebServiceToHandleDBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AWebServiceToHandleDBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AWebServiceToHandleDBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsResponse LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.AWebServiceToHandleDBSoap.DisplayAllProducts(LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequest request) {
            return base.Channel.DisplayAllProducts(request);
        }
        
        public LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.Product[] DisplayAllProducts() {
            LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequestBody();
            LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsResponse retVal = ((LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.AWebServiceToHandleDBSoap)(this)).DisplayAllProducts(inValue);
            return retVal.Body.DisplayAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsResponse> LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.AWebServiceToHandleDBSoap.DisplayAllProductsAsync(LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequest request) {
            return base.Channel.DisplayAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsResponse> DisplayAllProductsAsync() {
            LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.DisplayAllProductsRequestBody();
            return ((LU_SYSA14_2020_PartOne.ServiceReferenceWSTwo.AWebServiceToHandleDBSoap)(this)).DisplayAllProductsAsync(inValue);
        }
    }
}
