//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU_SYSA14_2020_PartOne.ServiceReferenceWSOne {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", ConfigurationName="ServiceReferenceWSOne.AWebServiceToHandleFilesSoap")]
    public interface AWebServiceToHandleFilesSoap {
        
        // CODEGEN: Generating message contract since element name fileName from namespace LU_SYSA14_2020_IntegrationTechnologies_CSG19 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/DisplayAFile", ReplyAction="*")]
        LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileResponse DisplayAFile(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/DisplayAFile", ReplyAction="*")]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileResponse> DisplayAFileAsync(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequest request);
        
        // CODEGEN: Generating message contract since element name FindAllFileNamesInTheDirectoryResult from namespace LU_SYSA14_2020_IntegrationTechnologies_CSG19 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/FindAllFileNamesInTheDirectory", ReplyAction="*")]
        LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryResponse FindAllFileNamesInTheDirectory(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/FindAllFileNamesInTheDirectory", ReplyAction="*")]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryResponse> FindAllFileNamesInTheDirectoryAsync(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisplayAFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DisplayAFile", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequestBody Body;
        
        public DisplayAFileRequest() {
        }
        
        public DisplayAFileRequest(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class DisplayAFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public DisplayAFileRequestBody() {
        }
        
        public DisplayAFileRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisplayAFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DisplayAFileResponse", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileResponseBody Body;
        
        public DisplayAFileResponse() {
        }
        
        public DisplayAFileResponse(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class DisplayAFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DisplayAFileResult;
        
        public DisplayAFileResponseBody() {
        }
        
        public DisplayAFileResponseBody(string DisplayAFileResult) {
            this.DisplayAFileResult = DisplayAFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAllFileNamesInTheDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAllFileNamesInTheDirectory", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequestBody Body;
        
        public FindAllFileNamesInTheDirectoryRequest() {
        }
        
        public FindAllFileNamesInTheDirectoryRequest(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FindAllFileNamesInTheDirectoryRequestBody {
        
        public FindAllFileNamesInTheDirectoryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAllFileNamesInTheDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAllFileNamesInTheDirectoryResponse", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryResponseBody Body;
        
        public FindAllFileNamesInTheDirectoryResponse() {
        }
        
        public FindAllFileNamesInTheDirectoryResponse(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class FindAllFileNamesInTheDirectoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.ArrayOfString FindAllFileNamesInTheDirectoryResult;
        
        public FindAllFileNamesInTheDirectoryResponseBody() {
        }
        
        public FindAllFileNamesInTheDirectoryResponseBody(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.ArrayOfString FindAllFileNamesInTheDirectoryResult) {
            this.FindAllFileNamesInTheDirectoryResult = FindAllFileNamesInTheDirectoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AWebServiceToHandleFilesSoapChannel : LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.AWebServiceToHandleFilesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AWebServiceToHandleFilesSoapClient : System.ServiceModel.ClientBase<LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.AWebServiceToHandleFilesSoap>, LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.AWebServiceToHandleFilesSoap {
        
        public AWebServiceToHandleFilesSoapClient() {
        }
        
        public AWebServiceToHandleFilesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AWebServiceToHandleFilesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AWebServiceToHandleFilesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AWebServiceToHandleFilesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileResponse LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.AWebServiceToHandleFilesSoap.DisplayAFile(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequest request) {
            return base.Channel.DisplayAFile(request);
        }
        
        public string DisplayAFile(string fileName) {
            LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequestBody();
            inValue.Body.fileName = fileName;
            LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileResponse retVal = ((LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.AWebServiceToHandleFilesSoap)(this)).DisplayAFile(inValue);
            return retVal.Body.DisplayAFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileResponse> LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.AWebServiceToHandleFilesSoap.DisplayAFileAsync(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequest request) {
            return base.Channel.DisplayAFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileResponse> DisplayAFileAsync(string fileName) {
            LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.DisplayAFileRequestBody();
            inValue.Body.fileName = fileName;
            return ((LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.AWebServiceToHandleFilesSoap)(this)).DisplayAFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryResponse LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.AWebServiceToHandleFilesSoap.FindAllFileNamesInTheDirectory(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequest request) {
            return base.Channel.FindAllFileNamesInTheDirectory(request);
        }
        
        public LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.ArrayOfString FindAllFileNamesInTheDirectory() {
            LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequestBody();
            LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryResponse retVal = ((LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.AWebServiceToHandleFilesSoap)(this)).FindAllFileNamesInTheDirectory(inValue);
            return retVal.Body.FindAllFileNamesInTheDirectoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryResponse> LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.AWebServiceToHandleFilesSoap.FindAllFileNamesInTheDirectoryAsync(LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequest request) {
            return base.Channel.FindAllFileNamesInTheDirectoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryResponse> FindAllFileNamesInTheDirectoryAsync() {
            LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.FindAllFileNamesInTheDirectoryRequestBody();
            return ((LU_SYSA14_2020_PartOne.ServiceReferenceWSOne.AWebServiceToHandleFilesSoap)(this)).FindAllFileNamesInTheDirectoryAsync(inValue);
        }
    }
}
