//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU_SYSA14_2020_PartOne.ServiceReferenceERPOne {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string No_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string No_ {
            get {
                return this.No_Field;
            }
            set {
                if ((object.ReferenceEquals(this.No_Field, value) != true)) {
                    this.No_Field = value;
                    this.RaisePropertyChanged("No_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", ConfigurationName="ServiceReferenceERPOne.AWebServiceForCRONUSSoap")]
    public interface AWebServiceForCRONUSSoap {
        
        // CODEGEN: Generating message contract since element name no_ from namespace LU_SYSA14_2020_IntegrationTechnologies_CSG19 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/CreateEmployee", ReplyAction="*")]
        LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeResponse CreateEmployee(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/CreateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeResponse> CreateEmployeeAsync(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name no_ from namespace LU_SYSA14_2020_IntegrationTechnologies_CSG19 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/ViewEmployee", ReplyAction="*")]
        LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeResponse ViewEmployee(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/ViewEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeResponse> ViewEmployeeAsync(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name no_ from namespace LU_SYSA14_2020_IntegrationTechnologies_CSG19 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/UpdateEmployee", ReplyAction="*")]
        LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeResponse UpdateEmployee(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeResponse> UpdateEmployeeAsync(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name no_ from namespace LU_SYSA14_2020_IntegrationTechnologies_CSG19 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/DeleteEmployee", ReplyAction="*")]
        LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeResponse DeleteEmployee(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LU_SYSA14_2020_IntegrationTechnologies_CSG19/DeleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeResponse> DeleteEmployeeAsync(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployee", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequestBody Body;
        
        public CreateEmployeeRequest() {
        }
        
        public CreateEmployeeRequest(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class CreateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no_;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string city;
        
        public CreateEmployeeRequestBody() {
        }
        
        public CreateEmployeeRequestBody(string no_, string firstName, string lastName, string jobTitle, string address, string city) {
            this.no_ = no_;
            this.firstName = firstName;
            this.lastName = lastName;
            this.jobTitle = jobTitle;
            this.address = address;
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployeeResponse", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeResponseBody Body;
        
        public CreateEmployeeResponse() {
        }
        
        public CreateEmployeeResponse(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class CreateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateEmployeeResult;
        
        public CreateEmployeeResponseBody() {
        }
        
        public CreateEmployeeResponseBody(bool CreateEmployeeResult) {
            this.CreateEmployeeResult = CreateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewEmployee", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequestBody Body;
        
        public ViewEmployeeRequest() {
        }
        
        public ViewEmployeeRequest(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class ViewEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no_;
        
        public ViewEmployeeRequestBody() {
        }
        
        public ViewEmployeeRequestBody(string no_) {
            this.no_ = no_;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewEmployeeResponse", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeResponseBody Body;
        
        public ViewEmployeeResponse() {
        }
        
        public ViewEmployeeResponse(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class ViewEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.Employee[] ViewEmployeeResult;
        
        public ViewEmployeeResponseBody() {
        }
        
        public ViewEmployeeResponseBody(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.Employee[] ViewEmployeeResult) {
            this.ViewEmployeeResult = ViewEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployee", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequestBody Body;
        
        public UpdateEmployeeRequest() {
        }
        
        public UpdateEmployeeRequest(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class UpdateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no_;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string city;
        
        public UpdateEmployeeRequestBody() {
        }
        
        public UpdateEmployeeRequestBody(string no_, string firstName, string lastName, string jobTitle, string address, string city) {
            this.no_ = no_;
            this.firstName = firstName;
            this.lastName = lastName;
            this.jobTitle = jobTitle;
            this.address = address;
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeResponse", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeResponseBody Body;
        
        public UpdateEmployeeResponse() {
        }
        
        public UpdateEmployeeResponse(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class UpdateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmployeeResult;
        
        public UpdateEmployeeResponseBody() {
        }
        
        public UpdateEmployeeResponseBody(string UpdateEmployeeResult) {
            this.UpdateEmployeeResult = UpdateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployee", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequestBody Body;
        
        public DeleteEmployeeRequest() {
        }
        
        public DeleteEmployeeRequest(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class DeleteEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no_;
        
        public DeleteEmployeeRequestBody() {
        }
        
        public DeleteEmployeeRequestBody(string no_) {
            this.no_ = no_;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployeeResponse", Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19", Order=0)]
        public LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeResponseBody Body;
        
        public DeleteEmployeeResponse() {
        }
        
        public DeleteEmployeeResponse(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="LU_SYSA14_2020_IntegrationTechnologies_CSG19")]
    public partial class DeleteEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteEmployeeResult;
        
        public DeleteEmployeeResponseBody() {
        }
        
        public DeleteEmployeeResponseBody(bool DeleteEmployeeResult) {
            this.DeleteEmployeeResult = DeleteEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AWebServiceForCRONUSSoapChannel : LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AWebServiceForCRONUSSoapClient : System.ServiceModel.ClientBase<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap>, LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap {
        
        public AWebServiceForCRONUSSoapClient() {
        }
        
        public AWebServiceForCRONUSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AWebServiceForCRONUSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AWebServiceForCRONUSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AWebServiceForCRONUSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeResponse LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap.CreateEmployee(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployee(request);
        }
        
        public bool CreateEmployee(string no_, string firstName, string lastName, string jobTitle, string address, string city) {
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequestBody();
            inValue.Body.no_ = no_;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.address = address;
            inValue.Body.city = city;
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeResponse retVal = ((LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap)(this)).CreateEmployee(inValue);
            return retVal.Body.CreateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeResponse> LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap.CreateEmployeeAsync(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeResponse> CreateEmployeeAsync(string no_, string firstName, string lastName, string jobTitle, string address, string city) {
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.CreateEmployeeRequestBody();
            inValue.Body.no_ = no_;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.address = address;
            inValue.Body.city = city;
            return ((LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap)(this)).CreateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeResponse LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap.ViewEmployee(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequest request) {
            return base.Channel.ViewEmployee(request);
        }
        
        public LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.Employee[] ViewEmployee(string no_) {
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequestBody();
            inValue.Body.no_ = no_;
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeResponse retVal = ((LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap)(this)).ViewEmployee(inValue);
            return retVal.Body.ViewEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeResponse> LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap.ViewEmployeeAsync(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequest request) {
            return base.Channel.ViewEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeResponse> ViewEmployeeAsync(string no_) {
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.ViewEmployeeRequestBody();
            inValue.Body.no_ = no_;
            return ((LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap)(this)).ViewEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeResponse LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap.UpdateEmployee(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployee(request);
        }
        
        public string UpdateEmployee(string no_, string firstName, string lastName, string jobTitle, string address, string city) {
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequestBody();
            inValue.Body.no_ = no_;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.address = address;
            inValue.Body.city = city;
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeResponse retVal = ((LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap)(this)).UpdateEmployee(inValue);
            return retVal.Body.UpdateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeResponse> LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap.UpdateEmployeeAsync(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeResponse> UpdateEmployeeAsync(string no_, string firstName, string lastName, string jobTitle, string address, string city) {
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.UpdateEmployeeRequestBody();
            inValue.Body.no_ = no_;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.address = address;
            inValue.Body.city = city;
            return ((LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap)(this)).UpdateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeResponse LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap.DeleteEmployee(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployee(request);
        }
        
        public bool DeleteEmployee(string no_) {
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequestBody();
            inValue.Body.no_ = no_;
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeResponse retVal = ((LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap)(this)).DeleteEmployee(inValue);
            return retVal.Body.DeleteEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeResponse> LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap.DeleteEmployeeAsync(LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeResponse> DeleteEmployeeAsync(string no_) {
            LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequest inValue = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequest();
            inValue.Body = new LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.DeleteEmployeeRequestBody();
            inValue.Body.no_ = no_;
            return ((LU_SYSA14_2020_PartOne.ServiceReferenceERPOne.AWebServiceForCRONUSSoap)(this)).DeleteEmployeeAsync(inValue);
        }
    }
}
